/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exemplos.Figuras;

/**
 * @author Gustavo
 *
 */
public class Circulo extends Figura{
    
	/**
	 * 
	 */
	private double raio;
	/**
	 * 
	 */
	private static final double PI = 3.14159;
	
	/**
	 * @param raio
	 */
	public Circulo(double raio) {
		super();
		valueCheck(raio);
		this.raio = raio;
	}
		
	/**
	 * @return the area
	 */
	@Override
	public double getArea() {
		return raio * raio * PI;
	}
	
}
