/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exemplos.uri1012;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

import exemplos.Figuras.Circulo;

public class CirculoTest {
	@Test
	public void testOne() {
		Circulo c1 = new Circulo(5.2);
		double expected = 84.949;
		double actual = c1.getArea();
		assertEquals(expected, actual, 0.001);
	}
	
	@Test
	public void testTwo() {
		Circulo c2 = new Circulo(15.2);
		double expected = 725.833;
		double actual = c2.getArea();
		assertEquals(expected, actual, 0.001);
	}
}
