/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exemplos.uri1012;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

import exemplos.Figuras.Figura;
import exemplos.Figuras.Triangulo;

public class TrianguloTest {
	@Test
	public void testOne() {
		Figura t1 = new Triangulo(3.00, 5.2);
		double expected = 7.800;
		double actual = t1.getArea();
		assertEquals(expected, actual, 0.001);
	}
	
	@Test
	public void testTwo() {
		Figura t2 = new Triangulo(12.7, 15.2);
		double expected = 96.520;
		double actual = t2.getArea();
		assertEquals(expected, actual, 0.001);
	}
	
}
